--- #YAML:1.0
name:                POE-Component-Cron
version:             0.019
abstract:            Schedule POE Events using a cron spec
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    DateTime:                      0
    DateTime::Event::Cron:         0
    DateTime::Event::Random:       0
    POE:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Chris Fedde <cfedde@littleton.co.us>
